### ISSUE TITLE
run can exit when drainChan is empty, but didn't update results just yet

### ISSUE THREAD

**Issue by drorspei** [drorspei/fassst#1]
There's a concurrency bug in `go/main.go:run`, where the anonymous go routine taking things out of `drainChan` can take the last element out, and just then the main loop in `go/main.go:run` can exit and then the function returns - before the anonymous go routine appends the last element to `results`.

Here is minimal code simulating this bug:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	for {
		if run() != 1 {
			panic(fmt.Errorf("bummer"))
		}
	}
}

func run() int {
	drainChan := make(chan int, 30)
	nameChan := make(chan int, 30)

	results := 0

	// foo
	go func() {
		drainChan <- 1
		nameChan <- 1
	}()

	// drain go routine
	go func() {
		<-drainChan
		results += 1
	}()

	// main loop
	<-nameChan

	for len(drainChan) > 0 {
		time.Sleep(100 * time.Millisecond)
	}

	return results
}
```

**Comment by Relvox** [comment]
So there are two races which can occur here:
1. `len(drainChan) > 0` can be true before the results are updates
2. `<-nameChan` and the loop are executed before `drainChan<-` adds the actual value.

In order to fix (1.) I've made the following changes

```go
// ...
// drain go routine
var eating bool
go func() {
	_, eating = <-drainChan
	results += 1
	eating = false
}()
// ...
for len(drainChan) > 0 || eating {
	time.Sleep(100 * time.Millisecond)
}
// ...
```

But that didn't work, which led me to discover (2.). SO then I added  a loop around `<-nameChan` like this:
```go
// main loop
var done bool
for !done || len(drainChan) > 0 || eating {
	select {
	case <-nameChan:
		done = true
	default:
		time.Sleep(100*time.Millisecond)
	}
}
```

Which seems to have solved it :)
